/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/sword.glb --transform 
Files: ./public/models/sword.glb [1.3MB] > C:\Users\spale\Projects\github\portfolio\sword-transformed.glb [96.16KB] (93%)
Author: Ethica (https://sketchfab.com/Ethica)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/scarlet-sword-adventure-time-edc10a7eb09245428fa7bf54f52967e6
Title: Scarlet Sword | Adventure Time
*/
"use client";

import React, { useRef } from 'react';
import { useFrame, useThree } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/sword.glb');

  // Slowly rotate the sword
  const model = useRef();
  useFrame(() => {
    model.current.rotation.z += 0.0025;
  });

  return (
    <group {...props}
      dispose={null}
      ref={model}
      position={[-0.5, 4, -1]}
      rotation={[1.6, 3.15, 1.55]}
      scale={0.3}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.standardSurface1} position={[0, 0, -1]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[1, 0.566, 1]} />
    </group>
  );
}

useGLTF.preload('/models/sword.glb');
